import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {projects as editorial,services} from './site-content.mjs';
const dist=new URL('./dist/',import.meta.url);
const assets=JSON.parse(await readFile(new URL('./project-assets.json',import.meta.url),'utf8'));
const projects=assets.map(p=>({...p,...editorial.find(e=>e.slug===p.slug)}));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=p=>`/work/${p.slug}.html`;
const arrowGlyph='↗\uFE0E';
const arrow=`<span class="text-arrow" aria-hidden="true">${arrowGlyph}</span>`;
const img=(image,alt='',eager=false,cls='')=>`<img ${cls?`class="${cls}"`:''} src="/${image.src}" width="${image.width}" height="${image.height}" alt="${esc(alt)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const profile='https://drive.google.com/file/d/1llPGVRoRnY4LaYLOzYs3kmq6hX93z_ny/view?usp=sharing';
function header(active=''){
  const links=[['about','About'],['services','Services'],['work','Work'],['contact',"Let's talk"]].map(([slug,label])=>`<a href="/${slug}.html" ${slug===active?'aria-current="page"':''} ${slug==='contact'?'class="nav-contact"':''}>${label}${slug==='contact'?arrow:''}</a>`).join('');
  return `<header class="toolbar site-toolbar"><a class="brand" href="/" aria-label="Toucan Studio, home"><img src="/assets/logo.png" alt="Toucan Studio" width="769" height="434"></a><nav class="desktop-nav" aria-label="Main navigation">${links}</nav><details class="mobile-menu"><summary>Menu <span aria-hidden="true">＋</span></summary><nav aria-label="Mobile navigation"><a href="/">Home</a>${links}</nav></details></header>`;
}
function footer(){return `<footer class="site-footer"><div><a href="/" class="footer-name">Toucan Studio<span aria-hidden="true">.</span></a><p>Stories with character.<br>Made in Tripoli, Libya.</p></div><nav aria-label="Footer navigation"><a href="/about.html">About</a><a href="/services.html">Services</a><a href="/work.html">Work</a><a href="/contact.html">Contact</a></nav><div class="footer-contact"><a href="mailto:info@toucan.ly">info@toucan.ly ${arrow}</a><a href="${profile}">Studio profile ${arrow}</a><span>Alnoflien st, Tripoli, Libya</span></div><div class="footer-bottom"><span>© Toucan Studio ${new Date().getFullYear()}</span><a href="#top">Back to top ↑</a></div></footer>`;}
const cta=()=>`<section class="page-cta"><p class="section-label">Your next chapter</p><div><h2>Have a spark?</h2><a class="button button-light" href="/contact.html">Let's make something ${arrow}</a></div></section>`;
function layout(title,description,active,body){return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#063b39"><meta name="description" content="${esc(description)}"><title>${esc(title)} — Toucan Studio</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/pages.css"><script type="module" src="/site.js"></script></head><body class="inner-page" id="top"><a class="skip-link" href="#main">Skip to content</a>${header(active)}<main id="main" tabindex="-1">${body}</main>${footer()}</body></html>\n`;}
function card(p,index=0){return `<article class="work-card" data-category="${esc(p.category)}"><a href="${url(p)}"><div class="work-image">${img(p.cover,'',index<2)}<span class="card-arrow text-arrow" aria-hidden="true">${arrowGlyph}</span></div><div class="card-caption"><h2>${esc(p.title)}</h2><span>${esc(p.category)}</span></div><p>${esc(p.line)}</p></a></article>`;}
const write=(name,html)=>writeFile(new URL(name,dist),html);
await mkdir(new URL('work/',dist),{recursive:true});

await write('about.html',layout('About','Meet Toucan, a creative studio in Tripoli working across branding, content and campaigns.','about',`
<section class="page-hero about-hero"><p class="section-label"><span class="status-dot"></span> Hello, we're Toucan.</p><h1>Creative minds.<br>Meaningful <span class="accent">connections.</span></h1><div class="hero-bottom"><span class="small-label">Independent spirit.<br>Tripoli, Libya.</span><p class="lede">We bring strategy and design together to help your brand find its voice, its character and its people.</p></div></section>
<section class="page-section about-introduction"><figure class="about-art"><img src="/assets/studio-art/about-curiosity.webp" width="1536" height="1024" alt="A blue-haired character in orange sleeves explores leaves and shapes in a sketchbook." fetchpriority="high"><figcaption>A little of the way we see the world.</figcaption></figure><div class="about-perspective"><p class="section-label">The studio</p><h2>Good work starts<br>with curiosity.</h2><div class="body-copy"><p>Every brand has something to say. We look for the idea that makes it distinctive, then find the right way to express it.</p><p>From our studio in Tripoli, we connect the thinking behind a brand with the way it looks, moves and speaks.</p><p>A clear point of view. Room to experiment. Care for the details.</p></div></div></section>
<section class="page-section green-section"><p class="section-label">How we think</p><h2>A little curiosity.<br>A lot of character.</h2><div class="principles"><article><span>01 / Listen</span><h3>Understand the spark.</h3><p>Start with the people, the purpose and the question the work needs to answer.</p></article><article><span>02 / Shape</span><h3>Find the right expression.</h3><p>Bring strategy and craft together, so every creative choice has a reason.</p></article><article><span>03 / Connect</span><h3>Think beyond the design.</h3><p>Make a story that feels consistent wherever your audience encounters it.</p></article></div></section>
<section class="page-section studio-onward"><div><p class="section-label">Get to know us</p><h2>From a point of view<br>to a world of possibilities.</h2></div><div class="studio-destinations"><a href="/services.html"><span><strong>Explore our capabilities</strong><small>How we can bring a story to life.</small></span>${arrow}</a><a href="${profile}"><span><strong>Our studio profile</strong><small>A closer introduction to Toucan.</small></span>${arrow}</a></div></section>${cta()}`));

await write('services.html',layout('Services','Six creative services, from brand strategy and identity to social content, campaigns and motion.','services',`
<section class="page-hero services-hero services-hero-illustrated"><div class="services-opening"><p class="section-label">What we do</p><h1>Thoughtfully<br>made. Full of<br><span class="peach">character.</span></h1><p class="lede">Strategy, design and storytelling.<br>Six disciplines, working together.</p><a class="text-link" href="#capabilities">Explore our capabilities <span aria-hidden="true">↓</span></a></div><figure class="services-opening-art"><img src="/assets/studio-art/services-craft.webp" width="1536" height="1024" alt="A purple-haired artist brings a family of colourful layouts together at a studio worktable." fetchpriority="high"></figure></section>
<nav class="service-jump" aria-label="Explore services">${services.map((s,i)=>`<a href="#${s.id}"><span>0${i+1}</span>${['Social media','Branding','Strategy','Campaigns','Motion','Content'][i]} <span aria-hidden="true">↓</span></a>`).join('')}</nav>
<section class="page-section capabilities-section" id="capabilities" aria-labelledby="capabilities-title"><div class="capabilities-heading"><div><p class="section-label">Our capabilities</p><h2 id="capabilities-title">The right mix<br>for your next chapter.</h2></div><p class="body-copy">A focused piece of work or a connected programme. We shape the disciplines around what your project needs.</p></div><div class="capabilities-grid">${services.map((s,i)=>`<article class="capability" id="${s.id}"><div class="capability-topline"><span class="capability-number">0${i+1}</span><a class="capability-enquire" href="/contact.html?service=${s.id}" aria-label="Enquire about ${s.name}">${arrow}</a></div><h3>${s.name}</h3><p>${s.text}</p><ul class="deliverables">${s.items.map(t=>`<li>${t}</li>`).join('')}</ul></article>`).join('')}</div></section>
<section class="page-section collaboration-section"><div><p class="section-label">Working together</p><h2>A clear direction.<br>Space for good ideas.</h2><a class="text-link" href="/contact.html">Tell us what you have in mind ${arrow}</a></div><ol class="collaboration-steps"><li><span>01</span><div><h3>Start with the brief</h3><p>The objective, the audience and the context give the work its direction.</p></div></li><li><span>02</span><div><h3>Shape it together</h3><p>Explore the idea, develop the creative and refine the details through conversation.</p></div></li><li><span>03</span><div><h3>Bring the pieces together</h3><p>Carry a consistent story through the formats and touchpoints your project calls for.</p></div></li></ol></section><section class="page-section work-signpost"><p>See how these disciplines come together.</p><a href="/work.html">Explore our work ${arrow}</a></section>${cta()}`));

await write('work.html',layout('Our work','Explore Toucan’s branding, illustration, social media and campaign projects.','work',`
<section class="page-hero work-hero"><p class="section-label"><span class="status-dot"></span> Our work</p><h1>Stories we've put<br>into the <span class="accent">world.</span></h1><div class="hero-bottom"><span class="small-label">A collection of ideas<br>with character.</span><p class="lede">Different brands. Different challenges.<br>The same belief in a story well told.</p></div></section>
<section class="page-section archive" aria-label="Project archive"><div class="archive-toolbar"><div class="work-filters" role="group" aria-label="Filter projects" hidden>${['All','Branding','Social media','Illustration','Campaigns'].map((s,i)=>`<button type="button" data-filter="${s}" aria-pressed="${i===0}">${s}</button>`).join('')}</div><p class="results-count" aria-live="polite" aria-atomic="true">11 projects</p></div><div class="work-grid">${projects.map(card).join('')}</div></section>${cta()}`));

await write('contact.html',layout("Let's talk",'Tell Toucan about your idea. Start a conversation with the creative studio in Tripoli.','contact',`
<section class="page-hero contact-hero"><p class="section-label"><span class="status-dot"></span> Your next chapter</p><h1>Every good story<br>starts with <span class="accent">hello.</span></h1><a class="text-link contact-form-jump" href="#enquiry-panel">Prepare an enquiry <span aria-hidden="true">↓</span></a></section>
<section class="page-section contact-layout"><aside class="contact-note contact-note-illustrated"><figure class="contact-art"><img src="/assets/studio-art/contact-hello.webp" width="1254" height="1254" alt="Toucan's dark-winged bird perched on an open envelope, ready for a new conversation." fetchpriority="high"></figure><div class="contact-note-copy"><p class="section-label">Let's make something together.</p><h2>Have a spark?<br>We're listening.</h2><p>A clear brief, a fresh direction or an idea still taking shape. We'd like to hear about it.</p><a class="contact-direct" href="mailto:info@toucan.ly">info@toucan.ly ${arrow}</a><div class="address-block"><span class="small-label">Find us</span><p>Alnoflien st<br>Tripoli, Libya</p></div></div></aside>
<div class="enquiry-panel" id="enquiry-panel"><p class="section-label">A few details to get us started</p><h2>What's on your mind?</h2><p id="enquiry-help">Build a short enquiry, then send it from your email app to <a href="mailto:info@toucan.ly">info@toucan.ly</a>.</p><noscript><p>Email us directly at <a href="mailto:info@toucan.ly">info@toucan.ly</a> with your project idea and the services you're interested in.</p></noscript><form id="enquiry-form" aria-describedby="enquiry-help" hidden><div class="form-row"><label>Your name <span>(required)</span><input name="name" autocomplete="name" required maxlength="100" placeholder="What should we call you?"></label><label>Email address <span>(required)</span><input name="email" type="email" autocomplete="email" required maxlength="200" placeholder="you@company.com"></label></div><div class="form-row"><label>Company or organisation <span>(optional)</span><input name="company" autocomplete="organization" maxlength="150" placeholder="Who are you working with?"></label><label>Phone <span>(optional)</span><input name="phone" type="tel" autocomplete="tel" maxlength="60" placeholder="Include your country code"></label></div><fieldset><legend>I'm interested in <span>(choose any)</span></legend><div class="service-options">${services.map(s=>`<label><input type="checkbox" name="services" value="${s.name}" data-service="${s.id}"><span>${s.name}</span></label>`).join('')}</div></fieldset><label>A little about your project <span>(required)</span><textarea name="message" rows="5" required maxlength="1500" placeholder="The idea, the challenge, your timing — whatever you'd like us to know."></textarea></label><button class="button button-dark" type="submit">Prepare my enquiry ${arrow}</button><p class="form-note">You'll review the email before sending it. This form doesn't submit or store your details.</p></form>
<section id="enquiry-preview" class="enquiry-preview" hidden aria-labelledby="preview-title"><h3 id="preview-title" tabindex="-1">Your enquiry is ready to review.</h3><label for="enquiry-text">Email draft</label><textarea id="enquiry-text" readonly rows="10"></textarea><div class="actions"><a id="open-email" class="button button-dark" href="mailto:info@toucan.ly">Open email app ${arrow}</a><button id="copy-enquiry" class="text-button" type="button">Copy enquiry</button><button id="edit-enquiry" class="text-button" type="button">Edit details</button></div><p>Nothing has been sent yet. If an email app doesn't open, copy the enquiry and email it to <a href="mailto:info@toucan.ly">info@toucan.ly</a>.</p><p id="copy-status" role="status"></p></section></div></section>`));

for(const [index,p] of projects.entries()){
  const next=projects[(index+1)%projects.length];
  await write(`work/${p.slug}.html`,layout(p.title,`${p.line} ${p.intro}`,'work',`
<section class="page-hero project-hero"><a class="back-link" href="/work.html">← All work</a><div class="project-kicker"><span>${esc(p.category)}</span><span>${String(index+1).padStart(2,'0')} / 11</span></div><h1>${esc(p.title)}</h1><p class="project-line">${esc(p.line)}</p></section>
<figure class="project-lead">${img(p.cover,`${p.title} — featured project artwork`,true)}</figure>
<section class="page-section project-story"><div><p class="section-label">The story</p><h2>${esc(p.intro)}</h2><dl class="project-facts"><div><dt>Client</dt><dd>${esc(p.client)}</dd></div><div><dt>Focus</dt><dd>${esc(p.category)}</dd></div></dl></div><div class="body-copy">${p.paragraphs.map(t=>`<p>${esc(t)}</p>`).join('')}${p.video?`<a class="text-link" href="${p.video}" target="_blank" rel="noopener">Watch the campaign film <span class="visually-hidden">on Vimeo (opens in a new tab)</span>${arrow}</a>`:''}</div></section>
<section class="page-section project-gallery" aria-labelledby="gallery-title"><div class="gallery-heading"><h2 id="gallery-title">The work, in detail.</h2><span>${p.gallery.length} images</span></div><div class="gallery-grid">${p.gallery.map((g,i)=>`<a class="gallery-item ${g.width/g.height>1.6?'gallery-wide':''}" href="/${g.src}" data-gallery data-caption="${esc(p.title)} · ${String(i+1).padStart(2,'0')} / ${p.gallery.length}" aria-label="Enlarge ${esc(p.title)} artwork ${i+1}">${img(g,`${p.title} — project artwork ${i+1}`)}<span class="gallery-zoom" aria-hidden="true">＋</span></a>`).join('')}</div></section>
<nav class="project-pagination page-section" aria-label="More projects"><a class="project-return" href="/work.html"><span aria-hidden="true">←</span> All work</a><a class="project-next" href="${url(next)}"><span class="small-label">Next story · ${esc(next.category)}</span><span>${esc(next.title)} ${arrow}</span></a></nav>
<dialog class="lightbox" aria-label="Project artwork viewer"><div class="lightbox-bar"><p id="lightbox-caption"></p><button type="button" data-close aria-label="Close image viewer">Close ×</button></div><img class="lightbox-image" alt=""><div class="lightbox-controls"><button type="button" data-previous aria-label="Previous image">←</button><span>Use arrow keys to explore</span><button type="button" data-next aria-label="Next image">→</button></div></dialog>`));
}

// Preserve the approved home story; give the portfolio section a focused selection.
let home=await readFile(new URL('index.html',dist),'utf8');
if(!home.includes('href="pages.css"'))home=home.replace('<link rel="stylesheet" href="styles.css">','<link rel="stylesheet" href="styles.css">\n  <link rel="stylesheet" href="pages.css">\n  <script type="module" src="site.js"></script>');
home=home.replace(/<header class="toolbar[\s\S]*?<\/header>/,header());
home=home.replace(/<footer[\s\S]*?<\/footer>/,footer());
home=home.replace('<body>','<body id="top">');
for(const p of projects)home=home.replaceAll(p.source,url(p));
home=home.replace('href="https://toucan.ly/#contact"','href="/contact.html"');
if(!home.includes('Meet the studio'))home=home.replace('What we can create together <span aria-hidden="true">↓</span></a>',`What we can create together <span aria-hidden="true">↓</span></a><br><a class="text-link dark-link" href="/about.html">Meet the studio ${arrow}</a>`);
if(!home.includes('Explore all services'))home=home.replace('<div class="service-list">',`<a class="text-link section-onward" href="/services.html">Explore all services ${arrow}</a>\n      <div class="service-list">`);
if(!home.includes('Browse the work archive'))home=home.replace('<h3 class="more-work-label">',`<a class="text-link section-onward" href="/work.html">Browse the work archive ${arrow}</a><h3 class="more-work-label">`);
const selected=['septimus-consulting','vanex','msh-mkanah'].map(slug=>projects.find(p=>p.slug===slug));
home=home.replace(/<section class="work-intro content-section" id="work"[\s\S]*?<\/section>/,`<section class="work-intro content-section" id="work" aria-labelledby="work-title"><div class="section-topline"><div class="section-heading"><p class="section-label">Selected work</p><h2 id="work-title">A few stories.<br>Many possibilities.</h2></div><a class="text-link" href="/work.html">View all our work ${arrow}</a></div><div class="home-selection">${selected.map(p=>`<a class="selected-project" href="${url(p)}"><div class="selected-project-art">${img(p.cover)}${arrow}</div><p>${esc(p.category)}</p><h3>${esc(p.title)}</h3></a>`).join('')}</div></section>`);
home=home.replace(/<span aria-hidden="true">↗(?:\uFE0E)?<\/span>/gu,arrow);
await write('index.html',home);
await writeFile(new URL('./page-routes.json',import.meta.url),JSON.stringify(['/','/about.html','/services.html','/work.html','/contact.html',...projects.map(url)],null,2)+'\n');
console.log(`Built 15 inner pages; connected the home page.`);
