// Editorial summaries grounded in the public project archive captured in planning/.
export const projects = [
  {slug:'septimus-consulting',category:'Branding',client:'Septimus Consulting',line:'An identity built on trust.',intro:'Roman references meet a clear, confident visual language for an overseas training and consulting agency.',paragraphs:['The name Septimus led the identity towards Roman patterns and a face with classical features. The aim was to connect that heritage with the confidence people look for in a training and consulting partner.','A black-and-white palette, clean logo lines and bold typography bring the system together. Each element supports a straightforward, formal expression of the brand.']},
  {slug:'hackathon',category:'Branding',client:'Hexa Connection',line:'Code meets the starting line.',intro:'A visual identity for a technological race, bringing the language of coding into the energy of a marathon.',paragraphs:['Coding symbols form the starting point for the Hackathon logo, with a dash reimagined as the beginning of a running track.','Created for an event during the COVID pandemic, the visual language pairs red and blue with textured backgrounds, hands and microbe-inspired shapes to reflect the urgency of that moment.']},
  {slug:'shake-up',category:'Illustration',client:'Shake Up',line:'A fresh dose of personality.',intro:'Digital illustration for product announcements and social campaigns, with Shake Up’s character at the centre.',paragraphs:['The work brings original digital drawings to Shake Up’s social media, supporting campaigns for new products and services.','Toucan’s illustration approach is adapted to the brand’s existing identity, creating a playful visual vocabulary across a wide range of campaign moments.']},
  {slug:'gorella-games',category:'Social media',client:'Gorella Games',line:'The story is in the cards.',intro:'Characters and patterns from the playing cards become the starting point for a story-led social campaign.',paragraphs:['The campaign draws on the world already present in the games. Familiar characters and visual patterns move from the cards into social content.','The result is an interactive creative direction designed to invite attention and participation through storytelling.']},
  {slug:'vanex',category:'Social media',client:'Vanex Shipping',line:'A brand always on the move.',intro:'A varied social presence that carries Vanex’s identity across services, campaigns and seasons.',paragraphs:['The work uses Vanex’s existing shapes, colours and patterns to give its social channels a fresh visual presence.','Different services and seasonal moments receive their own creative treatment, while a shared identity keeps the digital and advertising campaigns connected.']},
  {slug:'tripoli-optic-group',category:'Social media',client:'Tripoli Optic Group',line:'A clearer point of view.',intro:'Social content and marketing planning built around the Tripoli Optics identity and its audience.',paragraphs:['The collaboration brought interactive content and a consistent design approach to the brand’s social pages.','Social media reporting informed marketing plans, connecting creative decisions with an understanding of how the audience responded.']},
  {slug:'numo-pay',category:'Campaigns',client:'Moamalat · NUMO PAY',line:'Making a new way to pay familiar.',intro:'A launch campaign introducing an electronic payment service through promotional and educational content.',paragraphs:['The launch began with a marketing plan exploring the target audience and the advantages of the payment service.','A mix of visual approaches adapted Moamalat’s identity for the app, giving promotional messages and educational content a clear, contemporary presentation.']},
  {slug:'fornello',category:'Branding',client:'Fornello',line:'A new chapter, unmistakably Fornello.',intro:'A renewed restaurant identity shaped by Japanese visual references and the story of a reopening.',paragraphs:['The logo brings together a Hanko-inspired seal, a lotus flower and sushi with chopsticks. The seal expresses a distinctive name; the lotus marks renewal.','Red, black and white complete the identity, drawing on Japanese cultural references to express strength and stability.']},
  {slug:'biscotti',category:'Branding',client:'Biscotti',line:'Made with warmth. Shared with joy.',intro:'A visual identity inspired by family recipes, generous flavours and the energy of a growing small business.',paragraphs:['The identity needed to carry more than the variety of baked goods. It also had to express the warmth, support and invitation to share behind a business built on a family recipe.','Biscotti’s launch after winning the Innovation Garden business accelerator award provided another source of energy for a rich, expressive visual system.']},
  {slug:'msh-mkanah',category:'Campaigns',client:'Danish Refugee Council',line:'A serious message, a human story.',intro:'“Not Its Place”: an awareness campaign about the dangers of small arms in civilian life.',paragraphs:['Toucan prepared and launched the campaign on social media for the Danish Refugee Council, using digital illustration, video production and graphic design.','The visual approach was built for an interactive, fast-moving online campaign. The same artwork also supported printed materials for awareness activities on the ground.'],video:'https://vimeo.com/995415206'},
  {slug:'16-days-of-activism',category:'Campaigns',client:'Huna Libya',line:'Opening a conversation that matters.',intro:'Esmah Oonf: a campaign for Huna Libya during the international 16 Days of Activism.',paragraphs:['Created in collaboration with UNFPA Libya, the campaign addressed gender-based violence and human rights alongside the international “Color the World Orange” initiative.','Illustration, graphic design, photography, animation and video supported the conversation. The storytelling sought common ground that the audience could relate to.'],video:'https://vimeo.com/994745198'}
];
export const services=[
  {id:'social',name:'Social Media Management',lead:'Be part of the conversation.',text:'Give your brand a consistent voice and a recognisable presence. We bring content, design and planning together around the people you want to reach.',items:['Content planning','Social creative','Reporting & direction'],project:'tripoli-optic-group'},
  {id:'branding',name:'Graphic Design and Branding',lead:'Give your idea its own character.',text:'From the first mark to a complete visual language, we shape identities that tell people who you are and carry that story into the everyday details.',items:['Visual identity','Brand applications','Graphic design'],project:'septimus-consulting'},
  {id:'strategy',name:'Strategic Marketing',lead:'Start with a clear direction.',text:'Understand your audience, define what matters and give every creative decision a purpose. A strong plan creates the space for good ideas to grow.',items:['Audience understanding','Message development','Marketing planning'],project:'numo-pay'},
  {id:'campaigns',name:'Campaign Management',lead:'One story. Every touchpoint.',text:'Connect your message, content and channels into a campaign with a clear through line, from the first announcement to the conversation that follows.',items:['Campaign concepts','Launch planning','Creative coordination'],project:'msh-mkanah'},
  {id:'motion',name:'Motion Graphics and Animation',lead:'Let the story move.',text:'Turn a message into a sequence people can follow. Movement, timing and personality help bring brand stories and campaign ideas to life.',items:['Motion design','Animation','Campaign films'],project:'16-days-of-activism'},
  {id:'content',name:'Content Creation',lead:'Make something worth connecting with.',text:'Find the right expression for what your brand wants to say, through illustration, photography and visual storytelling made for its audience.',items:['Illustration','Photography','Visual storytelling'],project:'shake-up'}
];
